Developer/urls.py
from django.urls import path
from Developer.views import MainPage, DeveloperPage, ObjectPage, ApargPage


urlpatterns = [
    path('developer/<int:developer_id>', DeveloperPage, name='DeveloperPage'),
    path('developer/object/<int:general_id>', ObjectPage, name='ObjectPage'),
    path('developer/object/apartment/<int:object_id>', ApargPage, name='ApargPage'),
    path('', MainPage, name='MainPage'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Developer.urls')),
]

Developer/models.py
from django.db import models

class Developer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    address = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    website = models.URLField(max_length=50, blank=True)

Object/models.py
from django.db import models
from Developer.models import Developer
from Areal.models import Region, Settlement, Street, District

class Date(models.Model):
    QUARTER_TYPES = [
        ('1', 'I кв.'),
        ('2', 'II кв.'),
        ('3', 'III кв.'),
        ('4', 'IV кв.'),
    ]
    quarter = models.CharField(max_length=1, choices=QUARTER_TYPES, default='I')
    year = models.PositiveSmallIntegerField(blank=False)
    
    def __str__(self):
        return f'{self.year} {self.quarter}'


class General(models.Model):
    name = models.CharField(max_length=50)
    type_of_development_group =  models.CharField(max_length=50)
    brand = models.ForeignKey(Developer, on_delete=models.CASCADE, related_name='general_developer')
    military_mortgage = models.BooleanField(default=False)
    maternity_capital = models.BooleanField(default=False)
    start_of_residential_complex_construction = models.ForeignKey(Date, null=True, on_delete=models.SET_NULL, related_name='general_date_start')
    end_of_residential_complex = models.ForeignKey(Date, null=True, on_delete=models.SET_NULL, related_name='general_date_end')
    address = models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        return f'{self.name} {self.brand.name}'
    

class Object(models.Model):
    name = models.CharField(max_length=50)
    general = models.ForeignKey(General, on_delete=models.CASCADE, related_name='object_general')
    state = models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        return f'{self.name} {self.street}'
    
class Apartment(models.Model):
    TYPES = [
        ('0', 'Студия'),
        ('1', '1-комнатная'),
        ('2', '2-комнатная'),
        ('3', '3-комнатная'),
        ('4', '4-комнатная'),
        ('5', '5-комнатная'),
        ('6', '6-комнатная'),
        ('7', 'Многокомнатная'),
    ]
    rooms = models.CharField(max_length=1, choices=TYPES, default='0')
    min_square = models.FloatField(default=0.0)
    max_square = models.FloatField(default=0.0)
    min_cost = models.FloatField(default=0.0)
    max_cost = models.FloatField(default=0.0)
    count = models.PositiveIntegerField(default=0)
    name = models.CharField(max_length=50)
    object = models.ForeignKey(Object, on_delete=models.CASCADE, related_name='apartment_object')

Developer/forms.py
from django import forms


class SearchDeveloperForm(forms.Form):
    developer_name = forms.CharField(max_length=50, label='Застройщик', required=False)
    developer_address = forms.CharField(max_length=50, label='Адрес застройщика', required=False)
    developer_site = forms.CharField(max_length=50, label='Сайт застройщика', required=False)
    
    
class SearchGeneralForm(forms.Form):
    name = forms.CharField(max_length=50, label='Название ЖК', required=False)
    address = forms.CharField(max_length=50, label='Адрес ЖК', required=False)
    

Developer/views.py
import asyncio
from django.shortcuts import render, redirect
from django.http import HttpResponse
from Object.models import Date, General, Object, Apartment
from Areal.models import Region, District, Settlement, Street
from Developer.models import Developer
from django.core.paginator import Paginator
from Developer.forms import SearchDeveloperForm, SearchGeneralForm

import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from fake_useragent import UserAgent
from tqdm import tqdm
import random
import time
from threading import Thread


def MainPage(request):
    data = {}
    developer_list = []
    if request.method == 'GET':
        form = SearchDeveloperForm()
        for developer in Developer.objects.all():
            if General.objects.filter(brand=developer).exists():
                obj_count = len(General.objects.filter(brand=developer))
            developer_list.append(
                {
                    'developer': developer,
                    'obj_count': obj_count
                }
            )
        data['form'] = form
    else:
        form = SearchDeveloperForm(request.POST)
        #form.name.initial = 123
        #dict_request = dict(request.POST)
        #print(f'{form=}')
        #print(f'{request.POST.get("developer_name")=}') 
        dev_name = request.POST.get('developer_name')
        dev_address = request.POST.get('developer_address')
        dev_website = request.POST.get('developer_site')
        #print(f'{dev_name=}\n{dev_address=}\n{dev_website=}\n')
        if dev_name == '' and dev_address == '' and dev_website == '':
            return redirect('./')
        if Developer.objects.filter(name__icontains=dev_name).exists():
            if dev_name != '':
                for developer in Developer.objects.filter(name__icontains=dev_name):
                   obj_count = 0
                   if General.objects.filter(brand=developer).exists():
                        obj_count = len(General.objects.filter(brand=developer))
                   developer_list.append(
                        {
                            'developer': developer,
                            'obj_count': obj_count
                        }
                    )
        if Developer.objects.filter(address__icontains=dev_address).exists():
            if dev_address != '':
                for developer in Developer.objects.filter(address__icontains=dev_address):
                   obj_count = 0
                   if General.objects.filter(brand=developer).exists():
                        obj_count = len(General.objects.filter(brand=developer))
                   developer_list.append(
                        {
                            'developer': developer,
                            'obj_count': obj_count
                        }
                    )
        if Developer.objects.filter(website__icontains=dev_website).exists():
            if dev_website != '':
                for developer in Developer.objects.filter(website__icontains=dev_website):
                   obj_count = 0
                   if General.objects.filter(brand=developer).exists():
                        obj_count = len(General.objects.filter(brand=developer))
                   developer_list.append(
                        {
                            'developer': developer,
                            'obj_count': obj_count
                        }
                    )
        print(f'{dev_name=}\n{dev_address=}\n{dev_website=}')
        data['form'] = form
    paginator = Paginator(developer_list, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    data['page_obj'] = page_obj
    return render(request, 'index.html', data)


def DeveloperPage(request, developer_id):
    data = {}
    genegal_list = []
    if request.method == 'GET':
        data['form'] = SearchGeneralForm()
        if Developer.objects.filter(id=developer_id).exists():
            developer = Developer.objects.get(id=developer_id)
            data['developer'] = developer
            if General.objects.filter(brand=developer).exists():
                genegal_list = General.objects.filter(brand=developer)
    else:
        data['form'] = SearchGeneralForm(request.POST)
        general_name = request.POST.get('name')
        general_address = request.POST.get('address')
        if Developer.objects.filter(id=developer_id).exists():
            developer = Developer.objects.get(id=developer_id)
            data['developer'] = developer
            general_name_list = []
            general_address_list = []
            if general_name == '' and general_address == '':
                genegal_list = General.objects.filter(brand=developer)
            else:
                if general_name != '':
                    general_name_list = list(General.objects.filter(brand=developer, name__icontains=general_name))
                if general_address != '':
                    general_address_list = list(General.objects.filter(brand=developer, address__icontains=general_address))
                genegal_list = general_name_list + general_address_list
    paginator = Paginator(genegal_list, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    data['page_obj'] = page_obj
    return render(request, 'developer.html', data)


def ObjectPage(request, general_id):
    data = {}
    if General.objects.filter(id=general_id).exists():
        general = General.objects.get(id=general_id)
        data['general'] = general
        data['objects'] = Object.objects.filter(general=general)
    return render(request, 'object.html', data)


def ApargPage(request, object_id):
    data = {}
    if Object.objects.filter(id=object_id).exists():
        object = Object.objects.get(id=object_id)
        data['object'] = object
        data['apartments'] = Apartment.objects.filter(object=object)
    return render(request, 'apartment.html', data)

Object/views.py
from django.shortcuts import render

# Create your views here.

templates/apartment.html
{% extends "base_generic.html" %}
{% block content %}
<div id="content">
                <div class="container-fluid">
<div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary"><a href='/developer/{{object.general.brand.id}}'>Застройщик: {{object.general.brand.name}}</a> <a href='/developer/object/{{object.general.id}}'>Объект: {{object.general.name}}</a> {{object.name}}</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                    <div class="row"><div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">
                                                Название
                                            </th>
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">
                                                Комнатность
                                            </th>
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">
                                                Площадь
                                            </th>
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">
                                                Стоимость (мл. руб.)
                                            </th>
                                            <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">
                                                Количество
                                            </th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr><th rowspan="1" colspan="1">Название</th><th rowspan="1" colspan="1">Комнатность</th><th rowspan="1" colspan="1">Площадь</th><th rowspan="1" colspan="1">Стоимость (мл. руб.)</th><th rowspan="1" colspan="1">Количество</th>
                                    </tfoot>
                                    <tbody>
                                        {% for item in apartments %}
                                        <tr class="odd">
                                            <td>{{ item.name }}</td>
                                            <td>{{ item.get_rooms_display }}</td>
                                            <td>{{ item.min_square }}-{{ item.max_square }}</td>
                                            <td>{{ item.min_cost }}-{{ item.max_cost }}</td>
                                            <td>{{ item.count }}</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                </table>
                            </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
{% endblock %}

templates/base_generic.html
<html lang="en"><head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ERZ</title>

    <!-- Custom fonts for this template-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/4.1.4/css/sb-admin-2.css" integrity="sha512-gOfBez3ehpchNxj4TfBZfX1MDLKLRif67tFJNLQSpF13lXM1t9ffMNCbZfZNBfcN2/SaWvOf+7CvIHtQ0Nci2A==" crossorigin="anonymous" referrerpolicy="no-referrer">
 </head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3"> ERZ <sup>1.0</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>


            <li class="nav-item">
                <a class="nav-link" href="/">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Список застройщиков</span></a>
            </li>



        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="auth/login" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username}}</span>
                            </a>
                        </li>

                    </ul>

                </nav>
                {% block content %}{% endblock %}
            </div>
            <!-- End of Main Content -->



        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>





</body></html>

templates/developer.html
{% extends "base_generic.html" %}
{% block content %}
<div id="content">
                <div class="container-fluid">
<div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Застройщик: {{developer.name}}</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                    <div>
                                        <form method=POST>
                                        {% csrf_token %}
                                        {{ form.as_table }}
                                        <input type="submit" value="Поиск">
                                        </form>
                                </div>
                                    <div class="row"><div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    
                                    <thead>
                                        <tr role="row"><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Название</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Адрес</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Запланированная дата сдачи</th></tr>
                                    </thead>
                                    <tfoot>
                                        <tr><th rowspan="1" colspan="1">Название</th><th rowspan="1" colspan="1">Адрес</th><th rowspan="1" colspan="1">Запланированная дата сдачи</th>
                                    </tfoot>
                                    <tbody>
                                        {% for item in page_obj.object_list %}
                                        <tr class="odd">
                                            <td><a href='./object/{{item.id}}'>{{ item.name }}</a></td>
                                            <td>{{ item.address }}</td>
                                            <td>{{ item.end_of_residential_complex.get_quarter_display }} квартал {{ item.end_of_residential_complex.year }} года</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                </table>
                            </div>
                            <div class="pagination">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">&laquo; первая</a>
                                        <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                                    {% endif %}
                            
                                    <span class="current">
                                            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                                    </span>
                            
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">вперёд</a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                                    {% endif %}
                                </span>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
{% endblock %}

templates/index.html
{% extends "base_generic.html" %}
{% block content %}
<div id="content">
                <div class="container-fluid">
<div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Застройщики</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                    <div>
                                        <form method=POST>
                                        {% csrf_token %}
                                        {{ form.as_table }}
                                        <input type="submit" value="Поиск">
                                        </form>
                                </div>
                                    <div class="row"><div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    
                                    <thead>
                                        <tr role="row"><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Застройщик</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Адрес</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Номер телефона</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Сайт</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Объектов</th></tr>
                                    </thead>
                                    <tfoot>
                                        <tr><th rowspan="1" colspan="1">Застройщик</th><th rowspan="1" colspan="1">Адрес</th><th rowspan="1" colspan="1">Номер телефона</th><th rowspan="1" colspan="1">Сайт</th><th rowspan="1" colspan="1">Объектов</th></tr>
                                    </tfoot>
                                    <tbody>
                                        {% for item in page_obj.object_list %}
                                        <tr class="odd">
                                            <td><a href='/developer/{{item.developer.id}}'>{{ item.developer.name }}</a></td>
                                            <td>{{ item.developer.address }}</td>
                                            <td>{{ item.developer.phone }}</td>
                                            <td><a href='http://{{ item.developer.website }}'>{{ item.developer.website }}</a></td>
                                            <td>{{ item.obj_count }}</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                </table>
                            </div>
                            <div class="pagination">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">&laquo; первая</a>
                                        <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
                                    {% endif %}
                            
                                    <span class="current">
                                            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                                    </span>
                            
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">вперёд</a>
                                        <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
                                    {% endif %}
                                </span>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
{% endblock %}

templates/object.html
{% extends "base_generic.html" %}
{% block content %}
<div id="content">
                <div class="container-fluid">
<div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary"><a href='/developer/{{general.brand.id}}'>Застройщик: {{general.brand.name}}</a> Объект: {{general.name}}</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                    <div class="row"><div class="col-sm-12"><table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                    
                                    <thead>
                                        <tr role="row"><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Название</th><th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 216.125px;">Статус</th></tr>
                                    </thead>
                                    <tfoot>
                                        <tr><th rowspan="1" colspan="1">Название</th><th rowspan="1" colspan="1">Статус</th>
                                    </tfoot>
                                    <tbody>
                                        {% for item in objects %}
                                        <tr class="odd">
                                            <td><a href='./apartment/{{item.id}}'>{{ item.name }}</a></td>
                                            <td>{{ item.state }}</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                </table>
                            </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
{% endblock %}